login/urls.py
from django.urls import path
from . import views

app_name='login'
urlpatterns = [
    path('', views.manageLogin, name='login'),
    path('logout/', views.manageLogout, name='logout'),
]

srms/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('student/', include('student.urls')),
]

student/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'student'
urlpatterns = [
    path('all', views.studentsList, name='allstudentslist'),
    path('search', views.SearchStudentView.as_view(), name='searchstudent'),
    path('filters', views.viewFilterStudent, name='filterstudent'),
    path('filterResults', views.ViewFilterResults.as_view(), name='filterresults'),
    path('new', views.viewAddStudent, name='addstudent'),
    path('uploadFile', views.viewUploadFile, name='uploadfile'),
    path('postUploadFile', views.postUploadFile, name='postuploadfile'),
    path('registerStudent', views.addStudent, name='registerstudent'),
    path('view/?P<id>', views.ViewStudentRecord.as_view(), name='viewstudent'),
    path('update/?P<id>', views.UpdateStudentRecord.as_view(), name='updatestudent'),
    path('updateStudent/', views.updateStudent, name='updatestudentinfo'),
    path('updateMultipleStudents/', views.viewUpdateMultipleStudentRecords, name='updatemultiplestudentrecords'),
    path('postUpdateMultipleStudents/', views.postUpdateMultipleStudentRecords, name='postupdatemultiplestudentrecords'),
    path('delete/?P<id>', views.DeleteStudentRecord.as_view(), name='deletestudent'),
    path('deleteStudent/', views.deleteStudent, name='removestudent'),
    path('pageNotFound/', views.pageNotFound, name='pagenotfound'),
]

if settings.DEBUG:
	urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

student/models.py
from django.db import models

# Create your models here.

class Student(models.Model):
    # Some predefined choices
    GENDER_TYPES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    CAREER_PREFERENCE_TYPES = (
        ('H', 'Higher Studies'),
        ('J', 'Job'),
    )
    # Student's personal information
    id_no = models.CharField(primary_key=True, max_length=12)
    name = models.CharField(max_length=80)
    branch = models.CharField(max_length=2)
    admission_category = models.CharField(max_length=3)
    cast_category = models.CharField(max_length=5)
    gender = models.CharField(max_length=1, choices=GENDER_TYPES)
    dob = models.DateField()
    email_id = models.CharField(max_length=100)
    contact_no_1 = models.CharField(max_length=12)
    contact_no_2 = models.CharField(max_length=12)
    # Student's academic information
    ssc_result = models.DecimalField(max_digits=5, decimal_places=2)
    hsc_result = models.DecimalField(max_digits=5, decimal_places=2)
    diploma_result = models.DecimalField(max_digits=5, decimal_places=2)
    spi_sem_1 = models.DecimalField(max_digits=4, decimal_places=2)
    spi_sem_2 = models.DecimalField(max_digits=4, decimal_places=2)
    spi_sem_3 = models.DecimalField(max_digits=4, decimal_places=2)
    spi_sem_4 = models.DecimalField(max_digits=4, decimal_places=2)
    spi_sem_5 = models.DecimalField(max_digits=4, decimal_places=2)
    spi_sem_6 = models.DecimalField(max_digits=4, decimal_places=2)
    spi_sem_7 = models.DecimalField(max_digits=4, decimal_places=2)
    spi_sem_8 = models.DecimalField(max_digits=4, decimal_places=2)
    cpi = models.DecimalField(max_digits=4, decimal_places=2)
    # Student's address information
    address_1 = models.CharField(max_length=150)
    address_2 = models.CharField(max_length=150)
    address_3 = models.CharField(max_length=150)
    city = models.CharField(max_length=30)
    state = models.CharField(max_length=30)
    pin_code = models.CharField(max_length=10)
    # Student's placement/internship data
    career_preference = models.CharField(max_length=1, choices=CAREER_PREFERENCE_TYPES)
    internship = models.CharField(max_length=100)
    placement = models.CharField(max_length=100)
    salary = models.DecimalField(max_digits=12, decimal_places=2)
    other_placement_1 = models.CharField(max_length=100)
    other_placement_2 = models.CharField(max_length=100)
    # Batch year
    batch_year = models.IntegerField()

class Skill(models.Model):
    sid = models.BigAutoField(primary_key=True)
    # Student's skill set information
    stu_id = models.ForeignKey(Student, on_delete=models.CASCADE)
    skills = models.CharField(max_length=50)

class Achievements(models.Model):
    aid = models.BigAutoField(primary_key=True)
    # Student's achievements information
    stu_id = models.ForeignKey(Student, on_delete=models.CASCADE)
    achievement_details = models.CharField(max_length=50)

student/views.py
import os
import xlrd
import datetime
from datetime import date
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.views import generic
from django.core.files.storage import FileSystemStorage
from django.db.models import Q
from django.urls import reverse
from student.models import Student, Skill, Achievements
from django.core.paginator import Paginator

# Create your views here.
def studentsList(request):
    """
    Returns the list of all students from the database
    """
    students = Student.objects.all().order_by('-batch_year', 'name')
    paginator = Paginator(students, 10)
    pageNumber = request.GET.get('page')
    pageObject = paginator.get_page(pageNumber)
    return render(request=request, template_name = "student/view_student_list.html", context={'student_list':pageObject, 'totalStudents' : len(students)})

# For search student
class SearchStudentView(generic.ListView):
    context_object_name = 'search_results'
    template_name = 'student/view_student_list.html'

    def get_queryset(self):
        q = self.request.GET.get('q')
        if q == "":
            return HttpResponseRedirect(reverse('student:allstudentslist'))
        
        # Search by ID, Name, Company 
        query = Student.objects.filter(
            Q(id_no__icontains = q) |
            Q(name__icontains =  q) |
            Q(internship__icontains = q) |
            Q(placement__icontains = q)
        )
        return {'searchFlag' : True, 'students': query, 'totalSearchResults': len(query)}

# For filter students view only
def viewFilterStudent(request):
    # Returns the view only
    return render(request,"student/filter_student_records.html")

# Do filter work here
class ViewFilterResults(generic.ListView):
    context_object_name = 'filter_results'
    template_name = 'student/filter_student_records.html'

    def get_queryset(self):
        q_career_preference = self.request.GET.get('career_preference')
        q_company_name = self.request.GET.get('company_name')
        q_batch_year = self.request.GET.get('batch_year') if self.request.GET.get('batch_year') != '' else date.today().year
        q_cpi = self.request.GET.get('cpi') if self.request.GET.get('cpi') != '' else 0
        q_branch = self.request.GET.get('branch')
        q_admission_category = self.request.GET.get('admission_category')
        q_gender = self.request.GET.get('gender')
        q_cast_category = self.request.GET.get('cast_category')

        if q_admission_category == '' and self.request.GET.get('batch_year') == '' and q_branch == '' and q_career_preference == '' and q_cast_category == '' and q_company_name == '' and self.request.GET.get('cpi') == '' and q_gender == '':
            return {'filterFlag' : False, 'errMsg': 'Provide some filters first'}

        filteredQueryObj = Q(
            batch_year = q_batch_year,
            career_preference__icontains = q_career_preference,
            cpi__gte = q_cpi,
            branch__icontains = q_branch,
            admission_category__icontains = q_admission_category,
            gender__icontains = q_gender,
            cast_category__icontains = q_cast_category,
            placement__icontains = q_company_name
        ) | Q(
            batch_year = q_batch_year,
            career_preference__icontains = q_career_preference,
            cpi__gte = q_cpi,
            branch__icontains = q_branch,
            admission_category__icontains = q_admission_category,
            gender__icontains = q_gender,
            cast_category__icontains = q_cast_category,
            internship__icontains = q_company_name
        )
        # Search by ID, Name, Company
        query = Student.objects.filter(filteredQueryObj)
        if len(query) == 0:
            print('Empty filter results')
            return {'filterFlag' : False, 'errMsg': 'No student records found by applying filters'}
        return {'filterFlag' : True, 'students': query, 'totalFilterResults': len(query)}

# For get request
def viewAddStudent(request):
    return render(request,"student/add_student_record.html")

# For post request
def addStudent(request):
    if request.method == "POST":
        id_no = request.POST.get('id_no', False)
        name = request.POST.get('name', False)
        branch = request.POST.get('branch', False)
        admission_category = request.POST.get('admission_category', False)
        cast_category = request.POST.get('cast_category', False)
        gender = request.POST.get('gender', False)
        dob = request.POST.get('dob', False)
        email_id = request.POST.get('email_id', False)
        contact_no_1 = request.POST.get('contact_no_1', False)
        contact_no_2 = request.POST.get('contact_no_2', False)
        ssc_result = request.POST.get('ssc_result', False)
        hsc_result = request.POST.get('hsc_result', False)
        diploma_result = request.POST.get('diploma_result', False)
        spi_sem_1 = request.POST.get('spi_sem_1', False)
        spi_sem_2 = request.POST.get('spi_sem_2', False)
        spi_sem_3 = request.POST.get('spi_sem_3', False)
        spi_sem_4 = request.POST.get('spi_sem_4', False)
        spi_sem_5 = request.POST.get('spi_sem_5', False)
        spi_sem_6 = request.POST.get('spi_sem_6', False)
        spi_sem_7 = request.POST.get('spi_sem_7', False)
        spi_sem_8 = request.POST.get('spi_sem_8', False)
        cpi = request.POST.get('cpi', False)
        address_1 = request.POST.get('address_1', False)
        address_2 = request.POST.get('address_2', False)
        address_3 = request.POST.get('address_3', False)
        city = request.POST.get('city', False)
        state = request.POST.get('state', False)
        pin_code = request.POST.get('pin_code', False)
        career_preference = request.POST.get('career_preference', False)
        internship = request.POST.get('internship', False)
        placement = request.POST.get('placement', False)
        salary = request.POST.get('salary', False)
        other_placement_1 = request.POST.get('other_placement_1', False)
        other_placement_2 = request.POST.get('other_placement_2', False)

        # Student Model object
        student_obj = Student(
            id_no = id_no, 
            name = name, 
            branch = branch, 
            admission_category = admission_category,
            cast_category = cast_category,
            gender = gender,
            dob = dob,
            email_id = email_id,
            contact_no_1 = contact_no_1,
            contact_no_2 = contact_no_2,
            ssc_result = ssc_result,
            hsc_result = hsc_result,
            diploma_result = diploma_result,
            spi_sem_1 = spi_sem_1,
            spi_sem_2 = spi_sem_2,
            spi_sem_3 = spi_sem_3,
            spi_sem_4 = spi_sem_4,
            spi_sem_5 = spi_sem_5,
            spi_sem_6 = spi_sem_6,
            spi_sem_7 = spi_sem_7,
            spi_sem_8 = spi_sem_8,
            cpi = cpi,
            address_1 = address_1,
            address_2 = address_2,
            address_3 = address_3,
            city = city,
            state = state,
            pin_code = pin_code,
            career_preference = career_preference,
            internship = internship,
            placement = placement,
            salary = salary,
            other_placement_1 = other_placement_1,
            other_placement_2 = other_placement_2)

        # Saving model object
        student_obj.save()

        # For Skills model
        total_skills = request.POST.get('total_skills', 0)
        if total_skills != '':
            total_skills = int(total_skills)
            removed_sids = request.POST.get('removed_sids', [])
            if len(removed_sids) != 0:
                removed_sids = removed_sids.split(',')
                removed_sids = removed_sids[:-1]
            # Saving model object
            for i in range(total_skills):
                if str(i) not in removed_sids:
                    s = request.POST.get('skills[' + str(i) + ']')
                    print(s)
                    if s != '':
                        skill_obj = Skill(stu_id_id = id_no, skills = s)
                        skill_obj.save()

        # For Achievements model
        total_achievements = request.POST.get('total_achievements', 0)
        if total_achievements != '':
            total_achievements = int(total_achievements)
            removed_aids = request.POST.get('removed_aids', [])
            if len(removed_aids) != 0:
                removed_aids = removed_aids.split(',')
                removed_aids = removed_aids[:-1]
                # removed_aids = list(map(int, removed_aids[:-1]))
            # Saving model object
            for i in range(total_achievements):
                if str(i) not in removed_aids:
                    a = request.POST.get('achievements[' + str(i) + ']')
                    print(a)
                    if a != '':
                        achievement_obj = Achievements(stu_id_id = id_no, achievement_details = a)
                        achievement_obj.save()

    return HttpResponseRedirect(reverse('student:allstudentslist'))

# For GET request
def viewUploadFile(request):
    return render(request, "student/upload_file.html")

# For saving student records in file
def saveStudentRecordsFromFile(sheet):
    for idx in range(1, sheet.nrows):
        id_no = sheet.cell_value(idx, 0)
        if isinstance(id_no, float):
            id_no = int(id_no)
        name = sheet.cell_value(idx, 1)
        branch = sheet.cell_value(idx, 2)
        admission_category = sheet.cell_value(idx, 3)
        cast_category = sheet.cell_value(idx, 4)
        gender = sheet.cell_value(idx, 5)
        dob = sheet.cell_value(idx, 6)
        email_id = sheet.cell_value(idx, 7)
        contact_no_1 = str(sheet.cell_value(idx, 8))
        contact_no_2 = str(sheet.cell_value(idx, 9))

templates/student/_footer.html
{%load static%}
</div>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<!-- <script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script> -->

templates/student/_header.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="{% url 'student:allstudentslist'%}">Student Record Management System</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'student:allstudentslist'%}">Students</a>
              </li>
            <li class="nav-item">
              <a type="submit" class="nav-link" href="{% url 'login:logout'%}" >Logout</a>
            </li>
        </ul>
      </div>
    </div>
</nav>

<div class="container">

templates/student/delete_student_record.html
{% load static %}
<html lang="en">
    <head>
        <title>Delete Student Record</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    </head>
    <body>
        <!-- Header part -->
        {% include 'student/_header.html' %}

        <!-- Alert Message -->
        <div class="mt-2 text-center h2 mb-3">
            Are you sure you want to delete this record?
        </div>

        <!-- View Student's Personal Information -->
        <div class="card mb-3">
            <div class="card-header text-white bg-dark">
                Student's Personal Information
            </div>
            <div class="card-body bg-light">
                <table class="table table-borderless">
                    <tbody>
                        <tr>
                            <td><b>Batch Year:</b></td>
                            <td>{{student_obj.batch_year}}</td>
                        </tr>
                        <tr>
                            <td><b>Student Id:</b></td>
                            <td>{{student_obj.id_no}}</td>
                            <td><b>Name:</b></td>
                            <td>{{student_obj.name}}</td>
                        </tr>
                        <tr>
                            <td><b>Branch:</b></td>
                            <td>{{student_obj.branch}}</td>
                            <td><b>Admission Category:</b></td>
                            <td>{{student_obj.admission_category}}</td>
                        </tr>
                        <tr>
                            <td><b>Gender:</b></td>
                            <td>{% if student_obj.gender == 'M' %} Male {% else %} Female {% endif %}</td>
                            <td><b>Cast Category:</b></td>
                            <td>{{student_obj.cast_category}}</td>
                        </tr>
                        <tr>
                            <td><b>Date of Birth:</b></td>
                            <td>{{student_obj.dob}}</td>
                            <td><b>Email ID:</b></td>
                            <td>{{student_obj.email_id}}</td>
                        </tr>
                        <tr>
                            <td><b>Contact No. 1:</b></td>
                            <td>{{student_obj.contact_no_1}}</td>
                            <td><b>Contact No. 2:</b></td>
                            {% if student_obj.contact_no_2 %}
                                <td>{{student_obj.contact_no_2}}</td>
                            {% else %}
                                <td>-</td>
                            {% endif %}
                        </tr>
                        <tr>
                            <td><b>City:</b></td>
                            <td>{{student_obj.city}}</td>
                            <td><b>State:</b></td>
                            <td>{{student_obj.state}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        
        <!-- Buttons -->
        <div class="row text-center mt-3">
            <!-- Cancel and Go Back -->
            <div class="col">
                <a class="btn btn-primary mb-3" 
                    href="{% url 'student:viewstudent' id=student_obj.id_no %}"
                    style="width:auto">
                    Cancel and Go Back
                </a>
            </div>
            <div class="col">
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    Delete Record
                </button>
                
                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Delete Alert!</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                This will permanently delete the record of "<b>{{student_obj.name}}</b>"
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                <form action="{% url 'student:removestudent'%}" method="post">
                                    {%  csrf_token  %}
                                    <input type="hidden" name="id_no" value={{student_obj.id_no}}>
                                    <button type="submit" class="btn btn-danger" >Delete</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Footer part -->
        {% include 'student/_footer.html' %}
    </body>
</html>

templates/student/page_not_found.html
{% load static %}
<html lang="en">
    <head>
        <title>Page Not Found</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    </head>
    <body>
        <!-- Header part -->
        {% include 'student/_header.html' %}

        <div class="mt-5 text-center text-khaki display-4">
            Requested Page Not Found
        </div>
        <div class="mt-1 display-1 text-center">
            <div>\(o_o)/</div>
            <div>|__|</div>
            <div>_/ \_</div>    
        </div>

        <!-- Footer part -->
        {% include 'student/_footer.html' %}
    </body>
</html>

templates/student/view_student_list.html
{% load static %}
<html lang="en">
    <head>
        <title>Students List</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    </head>
    <body>
        <!-- Header part -->
        {% include 'student/_header.html' %}
        
        <h2 class="mt-2 mb-2 text-center">Students</h2>
        <!-- <hr class="bg-dark" /> -->

        <div class="d-md-flex align-items-baseline">
            <!-- Add Student button -->
            <div class="p-1 btn-group">
                <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                    Manage Student
                </button>
                <ul class="dropdown-menu bg-light" aria-labelledby="dropdownMenuLink">
                    <li>
                        <a class="dropdown-item" href="{% url 'student:uploadfile'%}"
                        style="width:auto">
                            Upload File
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="{% url 'student:addstudent'%}"    
                        style="width:auto">
                            Student Registration Form
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="{% url 'student:updatemultiplestudentrecords'%}"
                        style="width:auto">
                            Update Multiple Records
                        </a>
                    </li>
                </ul>
            </div>

            <!-- Search box -->
            <div class="me-auto p-1 bd-highlight flex-fill">
                <form action="{% url 'student:searchstudent' %}" method="GET" value="{{request.GET.q}}">
                    <div class="input-group">
                        <input class="form-control" type="text" name="q" id="searchString" 
                            placeholder="Search student records by Student ID, Name or Company"
                            value="{{request.GET.q}}" required>
                        <div class="input-group-append">
                            <input type="submit" class="btn btn-secondary" name="submit" value="Search"/>
                        </div>
                    </div>
                </form>
            </div>

            <!-- Apply filters -->
            <div class="p-1 btn-group">
                <a class="btn btn-primary" href="{% url 'student:filterstudent'%}">
                    Apply Filters
                </a>
            </div>
        </div>

        <!-- Show search results -->
        {% if search_results.searchFlag %}
            <h4 class="mt-1 mb-2">{{search_results.totalSearchResults}} Search Results Found</h4>
            <div class="list-group">
                {% for s in search_results.students %}
                    <a class="list-group-item bg-light border mb-2"
                        href="{% url 'student:viewstudent' id=s.id_no %}"
                        style="cursor: pointer;">
                        <div class="row">
                            <div class="col">
                                <i>ID</i> : <b>{{s.id_no}}</b>
                            </div>
                            <div class="col">
                                <i>Batch Year</i> : <b>{{s.batch_year}}</b>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <i>Name</i> : <b>{{s.name}}</b>
                            </div>
                            <div class="col">
                                <i>Contact</i> : <b>{% if s.contact_no_1 %} {{s.contact_no_1 | floatformat}} {% else %} {{s.contact_no_2 | floatformat}} {%endif%}</b>
                            </div>
                        </div>
                    </a>
                {% endfor %}
            </div>
            {% if search_results.totalSearchResults == 0 %}
                <div class="card mt-3">
                    <div class="card-header bg-light">
                        No student records found with word '<b>{{request.GET.q}}</b>'
                    </div>
                </div>
            {% endif %}
        {% endif %}
    
        <!-- Student list -->
        {%if student_list %}
            <!-- Total students -->
            <div class="row mb-3 mt-3">
                <div class="col font-weight-bold">
                    <b>Total Student Records : {{ totalStudents }}</b>
                </div>
            </div>
            <!-- Student list -->
            <table class="table table-hover">
                <!-- Student header -->
                <thead>
                    <tr>
                        <th>Student ID</th>
                        <th>Name</th>
                        <th>Branch</th>
                        <th>Admission Category</th>
                        <th>Batch Year</th>
                        <th>Contact</th>
                    </tr>
                </thead>
                <!-- Student rows -->
                <tbody>
                    {%for student in student_list%}
                        <tr>
                            <td>
                                <a href="{% url 'student:viewstudent' id=student.id_no %}">{{student.id_no}}</a>
                            </td>
                            <td>{{student.name}}</td>
                            <td>{{student.branch}}</td>
                            <td>{{student.admission_category}}</td>
                            <td>{{student.batch_year}}</td>
                            <td>
                                {% if student.contact_no_1 %} {{student.contact_no_1 | floatformat}} {% else %} {{student.contact_no_2 | floatformat}} {%endif%}
                            </td>
                        </tr>
                    {%endfor%}
                </tbody>
            </table>
        {% else %}
            {% if totalStudents == 0 %}
                <div class="card">
                    <div class="card-header text-dark">
                        Student list is empty
                    </div>
                </div>
            {% endif %}
        {% endif %}

        <!--Pagination-->
        {% if totalStudents > 10 %}
            <nav aria-label="Page navigation for students">
                <ul class="pagination justify-content-center">
                    {% if student_list.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ student_list.previous_page_number }}">Previous</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="True">Previous</a>
                        </li>
                    {% endif %}

                    {% if student_list.number|add:'-4' > 1 %}
                        <li class="page-item"><a class="page-link" href="?page={{ student_list.number|add:'-5' }}">&hellip;</a></li>
                    {% endif %}

                    {% for i in student_list.paginator.page_range %}
                        {% if student_list.number == i %}
                            <li class="page-item active" aria-current="page">
                                <span class="page-link">
                                    {{ i }}
                                </span>
                            </li>
                        {% elif i > student_list.number|add:'-5' and i < student_list.number|add:'5' %}
                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if student_list.paginator.num_pages > student_list.number|add:'4' %}
                        <li class="page-item"><a class="page-link" href="?page={{ student_list.number|add:'5' }}">&hellip;</a></li>
                    {% endif %}

                    {% if student_list.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ student_list.next_page_number }}">Next</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="True">Next</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
        <!--End of Pagination-->
        
        <!-- Footer part -->
        {% include 'student/_footer.html' %}
    </body>
</html>