login/urls.py
from django.urls import path
from . import views

app_name='login'
urlpatterns = [
    path('', views.manageLogin, name='login'),
    path('logout/', views.manageLogout, name='logout'),
]

srms/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('student/', include('student.urls')),
]

templates/view_login.html
{% load static %}
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Login to SRMS</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    </head>
    <body>
        <div class="p-3 fs-3 card-header bg-dark text-white text-center">
            Welcome to Student Record Management System Portal
        </div>
        <div class="py-2 container">
            <div class="row">
                <div class="col-lg text-center">
                    <img class="img-fluid" src="{% static 'images/login-image.jpg' %}">
                </div>
                <div class="col-lg">
                    <!-- For invalid credentials -->
                    {% if invalidUser == 'True' %}
                    <div class="mt-4 alert alert-danger text-white bg-danger">
                        *Invalid Username or Password
                    </div>
                    {% endif %}
                    <!-- Login box -->
                    <div class="mt-4 card bg-light">
                        <div class="card-header bg-dark text-white">
                            Log in
                        </div>
                        <div class="card-body">
                            <form method="post" action="{% url 'login:login'%}">
                                {%  csrf_token  %}
                                <div class="mt-1 form-group">
                                    <label class="form-label">Username : </label>
                                    <input type="text" name="usernm" class="form-control" placeholder="Username" required autofocus>
                                </div>
                                <div class="mt-2 form-group">
                                    <label class="form-label">Password : </label>
                                    <input type="password" name="passwd" class="form-control" placeholder="Password" required>
                                </div>
                                <div class="mt-3 form-group text-center">
                                    <input type="submit" value="Submit" class="btn btn-primary" name="Submit">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>